### ISSUE TITLE
fatal error: google/sparsetable: No such file or directory

### ISSUE THREAD

**Issue by Clementine-Issue-Importer** [clementine-player/Clementine#3321]
_From [samir.be...@gmail.com](https://code.google.com/u/104218008797085695310/) on November 29, 2012 03:52:43_

Clementine doesn't build without 'libsparsehash'.

Running 'git bisect' between last time I built (2012-10-11) and HEAD:

-- Found Qt4: /usr/bin/qmake (found suitable version "4.8.3", required is "4.5.0") 
-- Found Qt4: /usr/bin/qmake (found version "4.8.3") 
-- checking for module 'libgpod-1.0>=0.7.92'
--   package 'libgpod-1.0>=0.7.92' not found
-- checking for module 'libimobiledevice-1.0'
--   package 'libimobiledevice-1.0' not found
-- checking for module 'libusbmuxd'
--   package 'libusbmuxd' not found
-- Found Qt4: /usr/bin/qmake (found version "4.8.3") 
-- Building static qsqlite plugin

The following components will be built:
   D-Bus support
   Devices: Audio CD support
   Devices: DeviceKit backend
   Devices: MTP support
   Gnome sound menu integration
   Last.fm support
   Moodbar support
   Spotify support: core code
   Spotify support: non-GPL binary helper
   Visualisations
   Wiimote support

The following components WILL NOT be built:
   Crash reporting (disabled in CMake config)
   Devices: GIO device backend (disabled in CMake config)
   Devices: iPod Touch, iPhone, iPad support (missing libimobiledevice, libusbmuxd, iPod classic support)
   Devices: iPod classic support (missing libgpod)
   Google Drive support (missing Google sparsehash)
   Sparkle integration (missing Mac OS X, Sparkle)
   Spotify support: blob downloader (disabled in CMake config)

[...]

[100&#37;] Building CXX object ext/clementine-tagreader/CMakeFiles/clementine-tagreader.dir/moc_googledrivestream.cxx.o
In file included from /home/ramsi/src/clementine/build/ext/clementine-tagreader/moc_googledrivestream.cxx:10:0:
/home/ramsi/src/clementine/build/ext/clementine-tagreader/../../../ext/clementine-tagreader/googledrivestream.h:26:30: fatal error: google/sparsetable: No such file or directory
compilation terminated.
make[2]: **\* [ext/clementine-tagreader/CMakeFiles/clementine-tagreader.dir/moc_googledrivestream.cxx.o] Error 1
make[1]: **\* [ext/clementine-tagreader/CMakeFiles/clementine-tagreader.dir/all] Error 2
make: **\* [all] Error 2
db586ca00e41c67172280890a1f12af273bacbc7 is the first bad commit
commit db586ca00e41c67172280890a1f12af273bacbc7
Author: John Maguire john.maguire@gmail.com
Date:   Wed Nov 28 14:43:03 2012 +0100

```
Read tags from Ubuntu One files and add to local database.
```

:040000 040000 d5e67c9fd112c8b0fe03088d1c3acf6ee97eb3c6 657905bab6382908be96cc80a4a1082151dac83e M      data
:040000 040000 075460b29b6c2129865fa5f5f649793bdc0ce157 453fbcae9edad1ff434d7ed0c992a4d87b4547a6 M      ext
:040000 040000 3041b5dcf7d78abf209a912e06bc23ef8143543a b951ac76a777e13b792bd669bf9b04ffb0d50a7e M      src
bisect run success

_Original issue: http://code.google.com/p/clementine-player/issues/detail?id=3320_
