### ISSUE TITLE
Compilation problem on Slackware 13.0!

### ISSUE THREAD

**Issue by Clementine-Issue-Importer** [clementine-player/Clementine#297]
_From [gohanz69](https://code.google.com/u/102837921934121348007/) on May 09, 2010 08:30:16_

The last 0.3 Clementine fail to build on my Slackware 13.0 with Qt-4.5.1. 
This is the shell output.

clementine-0.3/build# make
[ 2&#37;] Built target qtsingleapplication
[ 3&#37;] Built target qxt
[ 3&#37;] Building CXX object 
src/CMakeFiles/clementine_lib.dir/mainwindow.cpp.o
In file included from /tmp/txz/clementine-
0.3/src/analyzers/analyzercontainer.h:24,
from /tmp/txz/clementine-0.3/build/src/ui_mainwindow.h:29,
from /tmp/txz/clementine-0.3/src/mainwindow.h:26,
from /tmp/txz/clementine-0.3/src/mainwindow.cpp:17:
/tmp/txz/clementine-0.3/src/analyzers/analyzerbase.h:19:37: error: 
QGLWidget: No such file or directory
In file included from /tmp/txz/clementine-0.3/src/playlist.h:26,
from /tmp/txz/clementine-0.3/src/playlistview.h:20,
from /tmp/txz/clementine-0.3/build/src/ui_mainwindow.h:33,
from /tmp/txz/clementine-0.3/src/mainwindow.h:26,
from /tmp/txz/clementine-0.3/src/mainwindow.cpp:17:
/tmp/txz/clementine-0.3/src/song.h:24:21: error: QSqlQuery: No such file or 
directory
In file included from /tmp/txz/clementine-0.3/src/library.h:24,
from /tmp/txz/clementine-0.3/src/playlistview.h:21,
from /tmp/txz/clementine-0.3/build/src/ui_mainwindow.h:33,
from /tmp/txz/clementine-0.3/src/mainwindow.h:26,
from /tmp/txz/clementine-0.3/src/mainwindow.cpp:17:
/tmp/txz/clementine-0.3/src/librarybackend.h:21:21: error: QSqlError: No 
such file or directory
/tmp/txz/clementine-0.3/src/librarybackend.h:22:24: error: QSqlDatabase: No 
such file or directory
In file included from /tmp/txz/clementine-0.3/src/mainwindow.cpp:18:
/tmp/txz/clementine-0.3/src/player.h:46:25: error: QDBusArgument: No such 
file or directory
In file included from /tmp/txz/clementine-0.3/src/lastfmservice.h:29,
from /tmp/txz/clementine-0.3/src/mainwindow.cpp:26:
/usr/include/lastfm/Track:26:23: error: QDomElement: No such file or 
directory
In file included from /tmp/txz/clementine-0.3/src/lastfmservice.h:30,
from /tmp/txz/clementine-0.3/src/mainwindow.cpp:26:
/usr/include/lastfm/ws.h:26:25: error: QNetworkReply: No such file or 
directory
In file included from /tmp/txz/clementine-0.3/src/mainwindow.cpp:26:
/tmp/txz/clementine-0.3/src/lastfmservice.h:39:33: error: 
QNetworkAccessManager: No such file or directory
In file included from /tmp/txz/clementine-0.3/src/librarybackend.h:28,
from /tmp/txz/clementine-0.3/src/library.h:24,
from /tmp/txz/clementine-0.3/src/playlistview.h:21,
from /tmp/txz/clementine-0.3/build/src/ui_mainwindow.h:33,
from /tmp/txz/clementine-0.3/src/mainwindow.h:26,
from /tmp/txz/clementine-0.3/src/mainwindow.cpp:17:
/tmp/txz/clementine-0.3/src/libraryquery.h:47: error: ‘QSqlError’ does not 
name a type
/tmp/txz/clementine-0.3/src/libraryquery.h:59: error: field ‘query_’ has 
incomplete type
/tmp/txz/clementine-0.3/src/libraryquery.h: In member function 
‘LibraryQuery::operator const QSqlQuery&() const’:
/tmp/txz/clementine-0.3/src/libraryquery.h:51: error: ‘query_’ was not 
declared in this scope
In file included from /tmp/txz/clementine-0.3/src/library.h:24,
from /tmp/txz/clementine-0.3/src/playlistview.h:21,
from /tmp/txz/clementine-0.3/build/src/ui_mainwindow.h:33,
from /tmp/txz/clementine-0.3/src/mainwindow.h:26,
from /tmp/txz/clementine-0.3/src/mainwindow.cpp:17:
/tmp/txz/clementine-0.3/src/librarybackend.h: At global scope:
/tmp/txz/clementine-0.3/src/librarybackend.h:197: error: ‘QSqlDatabase’ 
does not name a type
/tmp/txz/clementine-0.3/src/librarybackend.h:198: error: ‘QSqlDatabase’ has 
not been declared
/tmp/txz/clementine-0.3/src/librarybackend.h:199: error: expected ‘,’ or 
‘...’ before ‘&’ token
/tmp/txz/clementine-0.3/src/librarybackend.h:199: error: ISO C++ forbids 
declaration of ‘QSqlError’ with no type
/tmp/txz/clementine-0.3/src/librarybackend.h:206: error: ‘QSqlDatabase’ has 
not been declared
In file included from /tmp/txz/clementine-0.3/src/mainwindow.cpp:18:
/tmp/txz/clementine-0.3/src/player.h:47: error: expected constructor, 
destructor, or type conversion before ‘&’ token
/tmp/txz/clementine-0.3/src/player.h:48: error: expected initializer before 
‘&’ token
In file included from /tmp/txz/clementine-0.3/src/lastfmservice.h:29,
from /tmp/txz/clementine-0.3/src/mainwindow.cpp:26:
/usr/include/lastfm/Track:85: error: expected ‘,’ or ‘...’ before ‘&’ token
/usr/include/lastfm/Track:132: error: ‘QDomElement’ does not name a type
In file included from /tmp/txz/clementine-0.3/src/lastfmservice.h:30,
from /tmp/txz/clementine-0.3/src/mainwindow.cpp:26:
/usr/include/lastfm/ws.h:152: error: ‘QNetworkReply::NetworkError’ has not 
been declared
In file included from /tmp/txz/clementine-0.3/src/mainwindow.cpp:26:
/tmp/txz/clementine-0.3/src/lastfmservice.h:182: error: field ‘network_’ 
has incomplete type
/usr/include/lastfm/global.h: In function ‘QString 
lastfm::qMetaEnumString(int, const char_) [with T = QNetworkReply]’:
/usr/include/lastfm/ws.h:154: instantiated from here
/usr/include/lastfm/global.h:51: error: incomplete type ‘QNetworkReply’ 
used in nested name specifier
make[2]: *_\* [src/CMakeFiles/clementine_lib.dir/mainwindow.cpp.o] Error 1
make[1]: **\* [src/CMakeFiles/clementine_lib.dir/all] Error 2
make: **\* [all] Error 2
root@argo:/tmp/txz/clementine-0.3/build#

_Original issue: http://code.google.com/p/clementine-player/issues/detail?id=297_
