### ISSUE TITLE
Fix build with GCC 4.9

### ISSUE THREAD

**Issue by dirtyepic** [clementine-player/Clementine#4279]
```
[ 42%] Building CXX object src/CMakeFiles/clementine_lib.dir/core/mergedproxymodel.cpp.o
cd /var/tmp/portage/media-sound/clementine-1.2.2/work/clementine-1.2.2_build/src && /usr/lib64/ccache/bin/x86_64-pc-linux-gnu-g++  -DBOOST_BIND_NO_PLACEHOLDERS -DBUILD_QXT_CORE -DBUILD_QXT_GUI -DQT_CORE_LIB -DQT_DBUS_LIB -DQT_GUI_LIB -DQT_NETWORK_LIB -DQT_NO_CAST_TO_ASCII -DQT_NO_URL_CAST_FROM_STRING -DQT_OPENGL_LIB -DQT_SQL_LIB -DQT_STRICT_ITERATORS -DQT_USE_QSTRINGBUILDER -DQT_WEBKIT_LIB -DQT_XML_LIB -DQXT_STATIC  -DQT_NO_DEBUG_OUTPUT -DNDEBUG -O2 -march=native -g -pipe -fdiagnostics-color  -Woverloaded-virtual -Wall -Wno-sign-compare -Wno-deprecated-declarations -Wno-unused-local-typedefs -Wno-unused-private-field -Wno-unknown-warning-option --std=c++0x -U__STRICT_ANSI__ -I/usr/include/taglib -isystem /usr/include/qt4 -isystem /usr/include/qt4/QtCore -I/usr/include/gstreamer-0.10 
[...]
-I/usr/include/qca2/QtCrypto    -o CMakeFiles/clementine_lib.dir/core/mergedproxymodel.cpp.o -c /var/tmp/portage/media-sound/clementine-1.2.2/work/Clementine-1.2.2/src/core/mergedproxymodel.cpp

In file included from ../../Clementine-1.2.2/src/core/mergedproxymodel.cpp:18:0:
../../Clementine-1.2.2/src/core/mergedproxymodel.h:23:12: error: 'std::placeholders' has not been declared
 using std::placeholders::_1;
            ^
../../Clementine-1.2.2/src/core/mergedproxymodel.h:24:12: error: 'std::placeholders' has not been declared
 using std::placeholders::_2;
```

Patch is at https://bugs.gentoo.org/507484

```
--- a/src/core/mergedproxymodel.h
+++ b/src/core/mergedproxymodel.h
@@ -19,6 +19,7 @@
 #define MERGEDPROXYMODEL_H

 #include <QAbstractProxyModel>
+#include <functional>

 using std::placeholders::_1;
 using std::placeholders::_2;
```
