### ISSUE TITLE
version 1.2.3 fails to build on Slackware64-14.1

### ISSUE THREAD

**Issue by pitchforks** [clementine-player/Clementine#4706]
qt-4.8.5

SlackBuild: http://slackbuilds.org/slackbuilds/14.1/audio/clementine/clementine.SlackBuild

Error log:

    Scanning dependencies of target clementine
    [100%] Building CXX object src/CMakeFiles/clementine.dir/main.cpp.o
    Linking CXX executable ../clementine
    CMakeFiles/clementine.dir/main.cpp.o: In function `main':
    main.cpp:(.text.startup+0x486): undefined reference to `qInitResources_translations()'
    collect2: error: ld returned 1 exit status
    make[2]: *** [clementine] Error 1
    make[1]: *** [src/CMakeFiles/clementine.dir/all] Error 2
    make: *** [all] Error 2

The SlackBuild maintainer can't reproduce it.

Older clementine-1.2.1 builds fine.
