### ISSUE TITLE
Doesn't compile on armv7 under Ubuntu 12.10 - OpenGL declaration issues

### ISSUE THREAD

**Issue by ghost** [clementine-player/Clementine#4284]
Seems to be related with https://bugs.launchpad.net/ubuntu/+source/qt4-x11/+bug/707794

Scanning dependencies of target clementine_lib
[ 55%] [ 55%] [ 55%] [ 55%] Building CXX object src/CMakeFiles/clementine_lib.dir/analyzers/analyzerbase.cpp.o
Building CXX object src/CMakeFiles/clementine_lib.dir/analyzers/analyzercontainer.cpp.o
Building CXX object src/CMakeFiles/clementine_lib.dir/analyzers/baranalyzer.cpp.o
Building CXX object src/CMakeFiles/clementine_lib.dir/analyzers/blockanalyzer.cpp.o
In file included from /tmp/Clementine/src/analyzers/analyzerbase.h:23:0,
                 from /tmp/Clementine/src/analyzers/blockanalyzer.h:8,
                 from /tmp/Clementine/src/analyzers/blockanalyzer.cpp:6:
/usr/include/GL/gl.h:163:17: error: conflicting declaration ‘typedef double GLdouble’
/usr/include/qt4/QtOpenGL/qgl.h:85:17: error: ‘GLdouble’ has a previous declaration as ‘typedef GLfloat GLdouble’
In file included from /tmp/Clementine/src/analyzers/analyzerbase.h:23:0,
                 from /tmp/Clementine/src/analyzers/baranalyzer.h:9,
                 from /tmp/Clementine/src/analyzers/baranalyzer.cpp:14:
/usr/include/GL/gl.h:163:17: error: conflicting declaration ‘typedef double GLdouble’
/usr/include/qt4/QtOpenGL/qgl.h:85:17: error: ‘GLdouble’ has a previous declaration as ‘typedef GLfloat GLdouble’
In file included from /usr/include/GL/gl.h:2087:0,
                 from /tmp/Clementine/src/analyzers/analyzerbase.h:23,
                 from /tmp/Clementine/src/analyzers/blockanalyzer.h:8,
                 from /tmp/Clementine/src/analyzers/blockanalyzer.cpp:6:
/usr/include/GL/glext.h:5327:19: error: conflicting declaration ‘typedef ptrdiff_t GLintptr’
/usr/include/GLES2/gl2.h:38:26: error: ‘GLintptr’ has a previous declaration as ‘typedef khronos_intptr_t GLintptr’
/usr/include/GL/glext.h:5328:19: error: conflicting declaration ‘typedef ptrdiff_t GLsizeiptr’
/usr/include/GLES2/gl2.h:39:26: error: ‘GLsizeiptr’ has a previous declaration as ‘typedef khronos_ssize_t GLsizeiptr’
In file included from /usr/include/GL/gl.h:2087:0,
                 from /tmp/Clementine/src/analyzers/analyzerbase.h:23,
                 from /tmp/Clementine/src/analyzers/baranalyzer.h:9,
                 from /tmp/Clementine/src/analyzers/baranalyzer.cpp:14:
/usr/include/GL/glext.h:5327:19: error: conflicting declaration ‘typedef ptrdiff_t GLintptr’
/usr/include/GLES2/gl2.h:38:26: error: ‘GLintptr’ has a previous declaration as ‘typedef khronos_intptr_t GLintptr’
/usr/include/GL/glext.h:5328:19: error: conflicting declaration ‘typedef ptrdiff_t GLsizeiptr’
/usr/include/GLES2/gl2.h:39:26: error: ‘GLsizeiptr’ has a previous declaration as ‘typedef khronos_ssize_t GLsizeiptr’
cc1plus: error: unrecognized command line option "-Wno-unknown-warning-option" [-Werror]
cc1plus: error: unrecognized command line option "-Wno-unused-private-field" [-Werror]
cc1plus: error: unrecognized command line option "-Wno-unused-local-typedefs" [-Werror]
cc1plus: all warnings being treated as errors
make[2]: **\* [src/CMakeFiles/clementine_lib.dir/analyzers/blockanalyzer.cpp.o] Error 1
make[2]: **\* Waiting for unfinished jobs....
cc1plus: error: unrecognized command line option "-Wno-unknown-warning-option" [-Werror]
cc1plus: error: unrecognized command line option "-Wno-unused-private-field" [-Werror]
cc1plus: error: unrecognized command line option "-Wno-unused-local-typedefs" [-Werror]
cc1plus: all warnings being treated as errors
make[2]: **\* [src/CMakeFiles/clementine_lib.dir/analyzers/baranalyzer.cpp.o] Error 1
In file included from /tmp/Clementine/src/analyzers/analyzerbase.h:23:0,
                 from /tmp/Clementine/src/analyzers/analyzerbase.cpp:18:
/usr/include/GL/gl.h:163:17: error: conflicting declaration ‘typedef double GLdouble’
/usr/include/qt4/QtOpenGL/qgl.h:85:17: error: ‘GLdouble’ has a previous declaration as ‘typedef GLfloat GLdouble’
In file included from /usr/include/GL/gl.h:2087:0,
                 from /tmp/Clementine/src/analyzers/analyzerbase.h:23,
                 from /tmp/Clementine/src/analyzers/analyzerbase.cpp:18:
/usr/include/GL/glext.h:5327:19: error: conflicting declaration ‘typedef ptrdiff_t GLintptr’
/usr/include/GLES2/gl2.h:38:26: error: ‘GLintptr’ has a previous declaration as ‘typedef khronos_intptr_t GLintptr’
/usr/include/GL/glext.h:5328:19: error: conflicting declaration ‘typedef ptrdiff_t GLsizeiptr’
/usr/include/GLES2/gl2.h:39:26: error: ‘GLsizeiptr’ has a previous declaration as ‘typedef khronos_ssize_t GLsizeiptr’
In file included from /tmp/Clementine/src/analyzers/analyzerbase.h:23:0,
                 from /tmp/Clementine/src/analyzers/analyzercontainer.h:25,
                 from /tmp/Clementine/src/analyzers/analyzercontainer.cpp:18:
/usr/include/GL/gl.h:163:17: error: conflicting declaration ‘typedef double GLdouble’
/usr/include/qt4/QtOpenGL/qgl.h:85:17: error: ‘GLdouble’ has a previous declaration as ‘typedef GLfloat GLdouble’
In file included from /usr/include/GL/gl.h:2087:0,
                 from /tmp/Clementine/src/analyzers/analyzerbase.h:23,
                 from /tmp/Clementine/src/analyzers/analyzercontainer.h:25,
                 from /tmp/Clementine/src/analyzers/analyzercontainer.cpp:18:
/usr/include/GL/glext.h:5327:19: error: conflicting declaration ‘typedef ptrdiff_t GLintptr’
/usr/include/GLES2/gl2.h:38:26: error: ‘GLintptr’ has a previous declaration as ‘typedef khronos_intptr_t GLintptr’
/usr/include/GL/glext.h:5328:19: error: conflicting declaration ‘typedef ptrdiff_t GLsizeiptr’
/usr/include/GLES2/gl2.h:39:26: error: ‘GLsizeiptr’ has a previous declaration as ‘typedef khronos_ssize_t GLsizeiptr’
cc1plus: error: unrecognized command line option "-Wno-unknown-warning-option" [-Werror]
cc1plus: error: unrecognized command line option "-Wno-unused-private-field" [-Werror]
cc1plus: error: unrecognized command line option "-Wno-unused-local-typedefs" [-Werror]
cc1plus: all warnings being treated as errors
make[2]: **\* [src/CMakeFiles/clementine_lib.dir/analyzers/analyzercontainer.cpp.o] Error 1
cc1plus: error: unrecognized command line option "-Wno-unknown-warning-option" [-Werror]
cc1plus: error: unrecognized command line option "-Wno-unused-private-field" [-Werror]
cc1plus: error: unrecognized command line option "-Wno-unused-local-typedefs" [-Werror]
cc1plus: all warnings being treated as errors
make[2]: **\* [src/CMakeFiles/clementine_lib.dir/analyzers/analyzerbase.cpp.o] Error 1
make[1]: **\* [src/CMakeFiles/clementine_lib.dir/all] Error 2
make: **\* [all] Error 2
➜  bin git:(master)

**Comment by docbender** [comment]
Hi, 
I had same problem on armv7l (AllWinner A20) under Ubuntu 14.04. Problem was solved, when I changed OpenGL declaration in file analyzers/analyzerbase.h and visualisations/projectmvisualisation.cpp. 
Instead:
```
    #include <GL/gl.h>
    #include <GL/glu.h>
```
I included:
```
    #include <GLES2/gl2.h>
```
