### ISSUE TITLE
Compiling from source on Ubuntu 19.10 (eoan) is impossible due to libqjson{0,-dev} no longer being in the Ubuntu repos

### ISSUE THREAD

**Issue by ronjouch** [clementine-player/Clementine#6430]
- [x] I checked the issue tracker for similar issues
- [x] I checked the [changelog](https://github.com/clementine-player/Clementine/blob/master/Changelog) if the issue is already resolved
- [x] I tried the latest Clementine build from [here](https://builds.clementine-player.org/)

### System information

Please provide information about your system and the version of Clementine used.

- Operating System: Ubuntu 19.10
- Clementine version: git master

### Expected behaviour / actual behaviour

I used to be able to build Clementine when I was running Ubuntu 19.04. After upgrading to 19.10, the build fails with

```
[ 11%] Building CXX object ext/libclementine-tagreader/CMakeFiles/libclementine-tagreader.dir/gmereader.cpp.o
/opt/clementine/3rdparty/libmygpo-qt/qjsonwrapper/Json.cpp:29:14: fatal error: qjson/parser.h: No such file or directory
   29 |     #include <qjson/parser.h>
      |              ^~~~~~~~~~~~~~~~
compilation terminated.
make[2]: *** [3rdparty/libmygpo-qt/CMakeFiles/mygpo-qt.dir/build.make:450: 3rdparty/libmygpo-qt/CMakeFiles/mygpo-qt.dir/qjsonwrapper/Json.cpp.o] Error 1
make[1]: *** [CMakeFiles/Makefile2:567: 3rdparty/libmygpo-qt/CMakeFiles/mygpo-qt.dir/all] Error 2
```
and indeed,

```bash
~ sudo apt install libqjson0 
Reading package lists... Done
Building dependency tree       
Reading state information... Done
Package libqjson0 is not available, but is referred to by another package.
This may mean that the package is missing, has been obsoleted, or
is only available from another source
E: Package 'libqjson0' has no installation candidate

~ ✘ sudo apt install libqjson-dev
Reading package lists... Done
Building dependency tree       
Reading state information... Done
E: Unable to locate package libqjson-dev
```

Doing an [Ubuntu package search for libqjson-dev](https://packages.ubuntu.com/search?searchon=names&suite=all&section=all&keywords=libqjson-dev), the package is indeed absent from the `eoan` (19.10) repos 😕.

What's a reasonable alternative to install it, and where? Then, [wiki / Compiling from Source](https://github.com/clementine-player/Clementine/wiki/Compiling-from-Source) should be updated.

**Comment by JulianVolodia** [comment]
I see. I was looking for that but fast search didn't get me response. Could you help us and ask on Ubuntu forum or their IRC what will be done with this packet on future (19.10 and later)?

Best

**Comment by rikmills** [comment]
qjson has been removed from Debian and Ubuntu as it uses Qt4 (obsolete unmaintained toolkit) and has had its functionality superseded by Qt5.

See: https://bugs.debian.org/cgi-bin/bugreport.cgi?bug=935705

Preferably Clementine should release a stable Qt5 release if it wants an up to date version in Ubuntu. We already have switched to a Qt5 git snapshot to drop the Qt4 build.

**Comment by ronjouch** [comment]
So, on to Qt5! 🙂.

@JulianVolodia / anyone: is the `qt5` branch usable these days, and up-to-date with `master`? Are the build instructions different? Also, can I help bringing this forward? (With testing, or specific blocker bugs preventing a release).

**Comment by rikmills** [comment]
I should also perhaps mention that removing Qt4 in its entirety is an ongoing task in Ubuntu and Debian. I can only speak for Ubuntu, but we would like to see Qt4 removed entirely from the repositories in 20.04 LTS to be released in April.

**Comment by paperbagcorner** [comment]
The qt5 branch has recently been merged into master. Building from source on Ubuntu 19.10 should work now.

**Comment by ronjouch** [comment]
> The qt5 branch has recently been merged into master. Building from source on Ubuntu 19.10 should work now.

Confirmed. Closing.
