### ISSUE TITLE
Clementine fails to build with glib >= 2.25

### ISSUE THREAD

**Issue by Clementine-Issue-Importer** [clementine-player/Clementine#662]
_From [herkt.mn](https://code.google.com/u/107440969884467526622/) on August 27, 2010 18:23:57_

What steps will reproduce the problem? 1. build Clementine with glib >= 2.25

What is the expected output?
Build completes without problems.

What do you see instead?

In file included from /usr/include/glib-2.0/gio/gio.h:49:0,  
                 from /home/lachs0r/tmp/clementine-player-read-only/src/devices/giolister.h:22,
                 from /home/lachs0r/tmp/clementine-player-read-only/src/devices/devicemanager.cpp:39:
/usr/include/glib-2.0/gio/gdbusintrospection.h:151:25: error: expected unqualified-id before ‘protected’
/usr/include/glib-2.0/gio/gdbusintrospection.h:151:25: error: expected ‘;’ before ‘protected’ What version of the product are you using? On what operating system? SVN r1789 on openSUSE Factory Please provide any additional information below. Qt already defines the variable "signals" as "protected".

Workaround attached.

**Attachment:** [fix-glib.diff](http://code.google.com/p/clementine-player/issues/detail?id=662)

_Original issue: http://code.google.com/p/clementine-player/issues/detail?id=662_
